package com.angelis.tera.game.process.model.dialog.enums;

public enum DialogStringEnum {
    DIALOG(1),
    QUEST(2),
    SHOP(3),
    BANK(4),
    CREATEGUILD(5),
    LEARNSKILLS(6),
    AVAILABLEQUESTS(7),
    MAILBOX(8),
    VIEWBROKERAGE(9),

    REFINEITEMS(11),
    FLIGHTPOINTS(12),
    APPLICANTREGISTRACTION(13),
    POLICY(14),
    TAXATION(15),
    OPENINCUBATOR(16),
    EQUIPPET(17),
    CRAFTING(18),
    TELEPORT(19),
    GUILD_BANK(20),
    VIEWBATTLEGROUPLIST(21),
    TAXATION2(22),
    TELEPORT2(23),
    EXCHANGEMEDALS(24),
    GUILDLEVELING(25),
    ACCEPTSTALWARTAURA(26),
    RESTORESTAMINA(27),
    VIEWBROKERAGE2(28),
    RESETPOINT(29),
    EXPANDINVENTORY(30),
    GUILDEMBLEM(31),
    MISSIONLISTCOMPLETE(32),
    REMODELEQUIPMENT(33),
    RESTOREEQUIPMENTAPPEARANCE(34),
    GUILDBANK(35),

    BUY_CRYSTALS(100),

    GUILDWARGOODS(120),

    SHOPFORPETS(130),

    REDEEMCUPRAENSIFORMS(140),
    REDEEMARGENTENSIFORMS(141),
    
    PVP_SHOP(141),

    CLAIMSUPPORTREWARDS(151),
    CLAIMPROGRESSREWARDS(152),
    CLAIMDEDICATIONREWARDS(153),
    CLAIMFRONTLINESREWARDS(154),

    BUY_GENERAL_GOODS(160),

    BUYBATTLEGROUNDSUPPLIES(170),

    WEAPONSMITHMATERIALS(180),
    ARMORSMITHMATERIALS(181),
    LEATHERWORKMATERIALS(182),
    TAILORINGMATERIALS(183),
    FOCUSCRAFTMATERIALS(184),
    ALCHEMYMATERIALS(185),

    WEAPONSMITHDESIGN(190),
    ARMORSMITHDESIGN(191),
    LEATHERWORKPATTERNS(192),
    TAILORINGDESIGN(193),
    FOCUSCRAFTDESIGN(194),
    ALCHEMYFORMULAS(195),

    BUYWARRIORGLYPHS(201),
    BUYLANCERGLYPHS(202),
    BUYSLAYERGLYPHS(203),
    BUYBERSERKERGLYPHS(204),
    BUYSORCERERGLYPHS(205),
    BUYARCHERGLYPHS(206),
    BUYMYSTICGLYPHS(207),
    BUYPRIESTGLYPHS(208),

    BUYARMOR(210),
    BUYWEAPONS(211),

    SUPPORTTOKENMELEEWEAPONS(221),
    PROGRESSTOKENMELEEWEAPONS(222),
    DEDICATIONTOKENMELEEWEAPONS(223),
    FRONTLINESTOKENMELEEWEAPONS(224),

    SUPPORTTOKENFOCI(231),
    PROGRESSTOKENFOCI(232),
    DEDICATIONTOKENFOCI(233),
    FRONTLINESFOCI(234),

    DYE_SHOP(240),

    VANARCHSPECIALTYSTORE(250),
    
    EQUIPMENTTEMPLATES(260),

    REDEEMOXBOWBADGES(270),
    REDEEMTRIALBADGES(271),
    REDEEMNECROTICBADGES(272),
    REDEEMDUALITYBADGES(273),
    REDEEMELDRITCHBADGES(274),
    REDEEMTRAININGBADGES(275),

    REDEEMLULUNPANGSGIFT(280),
    REDEEMYOKISGIFT(281),
    REDEEMSHANASGIFT(282),
    REDEEMNEPIRSGIFT(283),
    
    SPECIALITY_STORE(300),
    NPC_SHOP(321),

    EXCHANGEPRACTICUMBADGE(310),
    EXCHANGEDIREBADGE(311),
    EXCHANGEDIREBADGE2(312),
    EXCHANGEFEDERATIONCOIN(315),
    
    VELIKAHANDSTORE(324),
    
    ARKAI_FEATHER_EXCHANGE(330),
    HALLOWEN_CANDY(331),
    
    EXCHANGESILVERTALENT(510),
    EXCHANGEGOLDTALENT(511),
    
    TEST(9125),
    
    ;
    
    public final int value;
    
    DialogStringEnum(final int value) {
        this.value = value;
    }
}
