package com.angelis.tera.game.process.model.quest.enums;

public enum QuestNpcIconEnum {

    NONE(0),

    // STORY
    STORY_QUEST_REWARD(1),
    STORY_QUEST_PROCESS(2),
    STORY_QUEST_AVAILABLE(4),

    // STORY REPEATABLE
    STORY_REPEATABLE_QUEST_PROCESS(3),
    STORY_REPEATABLE_QUEST_AVAILABLE(5),

    // NORMAL
    NORMAL_QUEST_REWARD(6),
    NORMAL_QUEST_PROCESS(7),
    NORMAL_QUEST_AVAILABLE(9),

    // NORMAL REPEATABLE
    NORMAL_REPEATABLE_QUEST_PROCESS(8),
    NORMAL_REPEATABLE_QUEST_AVAILABLE(10),

    // GUILD
    GUILD_QUEST_REWARD(11),
    GUILD_QUEST_PROCESS(12),
    GUILD_QUEST_AVAILABLE(14),

    // GUILD REPEATABLE
    GUILD_REPEATABLE_QUEST_PROCESS(13),
    GUILD_REPEATABLE_AVAILABLE(15),

    // DAILY
    DAILY_QUEST_REWARD(16),
    DAILY_QUEST_PROCESS(17),
    DAILY_QUEST_AVAILABLE(19),

    // DAILY REPEATABLE
    DAILY_REPEATABLE_QUEST_PROCESS(18),
    DAILY_REPEATABLE_QUEST_AVAILABLE(20),

    // ALLIANCE
    ALLIANCE_QUEST_REWARD(23),
    ALLIANCE_QUEST_PROCESS(24),
    ALLIANCE_QUEST_AVAILABLE(26),

    // ALLIANCE REPEATABLE
    ALLIANCE_REPEATABLE_QUEST_PROCESS(25),
    ALLIANCE_REPEATABLE_QUEST_AVAILABLE(27),

    LEVEL_TOO_LOW(21),
    NEXUS_QUEST(22);

    public final int value;

    QuestNpcIconEnum(final int value) {
        this.value = value;
    }
}
