package com.angelis.tera.game.process.model.dialog.enums;

public enum DialogIconEnum {

    DEFAULT(1),
    DEFAULT_QUEST(4),

    // GUILD - BLUE
    GUILD_QUEST_REWARD(8),
    GUILD_QUEST_PROGRESS(13),
    GUILD_QUEST_START(23),
    
    // GUILD REPEATABLE
    GUILD_REPEATABLE_QUEST_PROGRESS(14),
    GUILD_REPEATABLE_QUEST_START(24),
    
    // STORY - RED
    STORY_QUEST_REWARD(9),
    STORY_QUEST_PROGRESS(15),
    STORY_QUEST_START(25),
    
    // STORY REPEATABLE
    STORY_REPEATABLE_QUEST_PROGRESS(16),
    STORY_REPEATABLE_QUEST_START(26),
    
    // NORMAL - YELLOW
    NORMAL_QUEST_REWARD(10),
    NORMAL_QUEST_PROGRESS(17),
    NORMAL_QUEST_START(27),
    
    // NORMAL REPEATABLE
    NORMAL_REPEATABLE_QUEST_PROGRESS(18),
    NORMAL_REPEATABLE_QUEST_START(28),
    
    // REPUTATION - GREEN
    REPUTATION_QUEST_REWARD(11),
    REPUTATION_QUEST_PROGRESS(19),
    REPUTATION_QUEST_START(29),
    
    // REPUTATION REPEATABLE
    REPUTATION_REPEATABLE_QUEST_PROGRESS(20),
    REPUTATION_REPEATABLE_QUEST_START(30),
    
    // ALLIANCE - PURPLE
    ALLIANCE_QUEST_REWARD(12),
    ALLIANCE_QUEST_PROGRESS(21),
    ALLIANCE_QUEST_START(31),
    
    // ALLIANCE REPEATABLE
    ALLIANCE_REPEATABLE_QUEST_PROGRESS(22),
    ALLIANCE_REPEATABLE_QUEST_START(32),

    CENTERED_PURPLE(33),
    CENTERED_GREEN(36);
    
    public final int value;
    
    DialogIconEnum(final int value) {
        this.value = value;
    }
}
